SELECT FIN.ORDEN_FINANC , CLI.NOMBRE_CLIENTE ,FECHA_FINANC , IFNULL(PAG.FECHA_VENCIMIENTO, DATE_ADD(FECHA_FINANC, INTERVAL 7 DAY))  AS FECHA_VENCIMIENTO
FROM FINANCIAMIENTOS FIN 
INNER JOIN CLIENTES CLI 
ON FIN.NUM_CLIENTE = CLI.NUM_CLIENTE 
LEFT JOIN  
	(
		SELECT ORDEN_FINANC , MAX(FECHA_PROX_VENC) AS FECHA_VENCIMIENTO
		FROM PAGOS 
		GROUP BY ORDEN_FINANC 	
	)	PAG
ON FIN.ORDEN_FINANC = PAG.ORDEN_FINANC 
WHERE IFNULL(PAG.FECHA_VENCIMIENTO, DATE_ADD(FECHA_FINANC, INTERVAL 7 DAY)) > SUBDATE(CURRENT_DATE,1) ;




SELECT CLI.NOMBRE_CLIENTE ,FECHA_FINANC , IFNULL(PAG.FECHA_VENCIMIENTO, DATE_ADD(FECHA_FINANC, INTERVAL 7 DAY))  AS FECHA_VENCIMIENTO
FROM FINANCIAMIENTOS FIN 
INNER JOIN CLIENTES CLI 
ON FIN.NUM_CLIENTE = CLI.NUM_CLIENTE 
LEFT JOIN  
	(
		SELECT ORDEN_FINANC , MAX(FECHA_PROX_VENC) AS FECHA_VENCIMIENTO
		FROM PAGOS 
		GROUP BY ORDEN_FINANC 	
	)	PAG
ON FIN.ORDEN_FINANC = PAG.ORDEN_FINANC 
WHERE IFNULL(PAG.FECHA_VENCIMIENTO, DATE_ADD(FECHA_FINANC, INTERVAL 7 DAY)) > SUBDATE(CURRENT_DATE,1) ;




SELECT CLI.NOMBRE_CLIENTE ,FIN.FECHA_FINANC, FIN.IMEI
FROM FINANCIAMIENTOS FIN 
INNER JOIN CLIENTES CLI 
ON FIN.NUM_CLIENTE = CLI.NUM_CLIENTE 
WHERE FIN.ORDEN_FINANC=1;

SELECT NUM_PAGO, FECHA_PAGO,FECHA_VENC,INTERES_PAGADO,CAPITAL_PAGADO,DESCTO_APLICADO,ABONO_EXTRA,CANTIDAD_RECIBIDA,CAMBIO_DEVUELTO
FROM PAGOS 
WHERE ORDEN_FINANC=1;

SELECT CLI.NOMBRE_CLIENTE ,FIN.FECHA_FINANC, FIN.IMEI, ART.DESCRIPCION_ART
FROM FINANCIAMIENTOS FIN 
INNER JOIN CLIENTES CLI 
ON FIN.NUM_CLIENTE = CLI.NUM_CLIENTE 
INNER JOIN ARTICULOS ART
ON FIN.CODIGO_ART= ART.CODIGO_ART
WHERE FIN.ORDEN_FINANC=1;


SELECT CLI.NOMBRE_CLIENTE ,FIN.FECHA_FINANC, FIN.IMEI, ART.DESCRIPCION_ART, OPPAGO.CODIGO_BLOQUEO,OPPAGO.MONTO_ADEUDO,OPPAGO.OPCION_1
FROM FINANCIAMIENTOS FIN 
INNER JOIN CLIENTES CLI 
ON FIN.NUM_CLIENTE = CLI.NUM_CLIENTE 
INNER JOIN ARTICULOS ART
ON FIN.CODIGO_ART= ART.CODIGO_ART
INNER JOIN OPCIONES_PAGO OPPAGO
ON OPPAGO.ORDEN_FINANC=FIN.ORDEN_FINANC
WHERE FIN.ORDEN_FINANC=1;